name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@2d330e3a3c70dd5a8401e744dcab06cc9da64c15
    with:
      itk-cmake-options: '-DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON'

  python-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@2d330e3a3c70dd5a8401e744dcab06cc9da64c15
    with:
      test-notebooks: true
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
