name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@4cf16c3a99f249d4b6c7157106ee1f800ce80322
    with:
      itk-cmake-options: '-DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON'

  python-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@4cf16c3a99f249d4b6c7157106ee1f800ce80322
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
