name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@66131916f30ada59b2cd91c333be2b4c14fbbd6a
    with:
      itk-cmake-options: '-DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON'

  python-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@66131916f30ada59b2cd91c333be2b4c14fbbd6a
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
