name: Build, test, package

on: [push,pull_request]

jobs:
  # removed for testing (TODO)

  python-build-workflow-tag-only:
    if: startsWith(github.ref, 'refs/tags')
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@03626a23c22246e89e36c7e918a158c440f9b099
    with:
      test-notebooks: true
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
