name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@c8dcc4972bda4862d0d7787219e163db9df31c94
    with:
      itk-cmake-options: '-DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON'

  python-build-workflow:
    uses: tbirdso/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@c8dcc4972bda4862d0d7787219e163db9df31c94
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
