name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@43b264a115eb9eb3a765ae4d28eccc485f19edd8
    with:
      itk-cmake-options: '-DITK_BUILD_DEFAULT_MODULES:BOOL=OFF -DITKGroup_Core:BOOL=ON'

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@43b264a115eb9eb3a765ae4d28eccc485f19edd8
    with:
      itk-python-package-tag: 'b0edcd41f87fb8516fb222759cfacce909754e3f'
      itk-python-package-org: 'tbirdso'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
